# Generated by Django 5.2.15 on 2026-06-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_time',
            field=models.DateTimeField(),
        ),
    ]
